server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HelloSpringBootTemplate0502Study
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  jpa:
    show-sql: true

